[workspace]

members = [
    './ast/',
    './lexer/',
    './lexer/repl/',
    './location/',
    './test/',
    './sexpr/',
    './syntax/',
    './tokens/',
    './wasm-api/',
]

[patch.crates-io]
memchr = { git = "https://github.com/CAD97/rust-memchr", branch = "patch-1" }
