unstable_features = true

# Stable
newline_style = "Native"
merge_derives = false

# Unstable
fn_single_line = true
match_block_trailing_comma = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
