[package]
name = "nafi-lexer"
version = "0.0.0"
publish = false

[dependencies]
nafi-tokens = { path = "../tokens/" }
nafi-interner = { path = "../interner/" }

lazy_static = "1.0"
log = "0.4"
memchr = "2.0"
regex = "0.2"

[dependencies.nom]
version = "4.0.0-alpha2"
features = ["verbose-errors", "regexp", "regexp_macros"]

[dependencies.nom_locate]
version = "0.3.0"
git = "https://github.com/CAD97/nom_locate.git"
rev = "a5d2afa8e1bbbb9e26455c201d6e40c9c1aad256"

[features]
nightly = ["lazy_static/nightly", "nom/nightly"]

[build-dependencies]
lazy_static = "1.0"
regex = "0.2"

[patch.crates-io.nom]
version = "4.0.0-alpha2"
git = "https://github.com/Geal/nom.git"
rev = "dd338670fb215a1ad2e35ed67dcbd96dae609595"
