[package]
name = "nafi-lexer"
version = "0.0.0"
publish = false

[dependencies]
nafi-tokens = { path = "../tokens/" }
nom_locate = { git = "https://github.com/nafi-lang/nom_locate.git" }
memchr = "2.0"
regex = "0.2"
single = "0.3"

[dependencies.nom]
git = "https://github.com/Geal/nom.git"
rev = "a53febdfdf99d16c0177f5c605bd98481a4ec50f"
features = ["nightly", "verbose-errors", "regexp", "regexp_macros"]

[dependencies.lazy_static]
version = "1.0"
features = ["nightly"]

[build-dependencies]
regex = "0.2"

[build-dependencies.lazy_static]
version = "1.0"
features = ["nightly"]

[[bin]]
name = "nafi-lexer-repl"
path = "./repl/main.rs"

[patch.crates-io.nom]
git = "https://github.com/Geal/nom.git"
rev = "a53febdfdf99d16c0177f5c605bd98481a4ec50f"
