[package]
name = "nafi-lexer"
version = "0.0.1"
publish = false

[dependencies]
error-chain = "0.11.0-rc.2"
nafi-tokens = { path = "../tokens/" }
nnom = { path = "../nnom/" }

[dependencies.num]
version = "0.1"
default-features = false
features = [ "bigint" ]

[[bin]]
name = "nafi-lexer-repl"
path = "repl/main.rs"
