[package]
name = "nafi-lexer"
version = "0.0.1"
publish = false

[dependencies]
error-chain = "0.11.0"
nafi-tokens = { path = "../tokens/" }
nnom = { path = "../nnom/" }

[[bin]]
name = "nafi-lexer-repl"
path = "repl/main.rs"
