[package]
name = "nafi-tokens"
version = "0.0.0"
publish = false

[dependencies]
num-bigint = "0.1"

[dependencies.lazy_static]
version = "1"
features = ["nightly"]

[dependencies.string-interner]
version = "0.6"
default-features = false
