[package]
name = "nafi-ast"
version = "0.0.0"
publish = false

[dependencies]
nafi-tokens = { path = "../tokens" }
nafi-location = { path = "../location" }
serde = "1.0"
serde_derive = "1.0"

[dependencies.num-bigint]
version = "0.2.0-git"
features = ["serde"]
git = "https://github.com/rust-num/num-bigint.git"
rev = "7424bbe0ea6a68e84af91ea7e0dd4ecc833c1806"
