[package]
name = "nafi-lexer-repl"
version = "0.0.0"
publish = false

[dependencies]
nafi-lexer = { path = "../../lexer/" }
nafi-tokens = { path = "../../tokens/" }
nafi-interner = { path = "../../interner/" }

quicli = "0.2"
